version: '3.1'

services:

  web:
    build: .
    restart: unless-stopped
    build:
        context: ./web
        dockerfile: ./Dockerfile
    ports:
      - 3000:80

  db:
    image: mariadb
    restart: always
    build:
        context: ./db
        dockerfile: ./Dockerfile
    environment:
        MYSQL_DATABASE: 'cdp'
        MYSQL_USER: 'cdp'
        MYSQL_PASSWORD: 'MYSQL_PASSWORD'
        MYSQL_ROOT_PASSWORD: 'MYSQL_PASSWORD'
    ports: 
        - "3306:3306"
    volumes:
        - ./db/sql:/var/db